### ISSUE TITLE
Bug in Bike Light "Kitt" example

### ISSUE THREAD

**Issue by LordSyd** [Codecademy/learn-circuitpython#8]
RainbowSpin throws error:

`Traceback (most recent call last):
File "code.py", line 72, in <module>
File "code.py", line 52, in rainbowSpin
File "code.py", line 28, in blinkLed
IndexError: tuple index out of range
`

**Comment by LordSyd** [comment]
changing the code to:

`def rainbowSpin(d=0.1):
    global colorIndex
    for x in range(0, 10):
        blinkLed(colorIndex, d, x, False)
        colorIndex += 1
        colorIndex = colorIndex % 10
    return`

fixes the issue. Seems to be an issue with the check for greater than and return to zero.

Using modulo is more error proof.

**Comment by LordSyd** [comment]
Opened a  pull request for the fixed code
